//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutualArtExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployees
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public decimal WorkHours { get; set; }
        public byte WageType { get; set; }
        public int Wage { get; set; }
        public byte Department { get; set; }
    }
}
